services:
  telebot:
    build: .
    container_name: telebot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./accounts.json:/app/accounts.json:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - proxy-net
      - data-net

networks:
  proxy-net:
    name: proxy-net
    external: true
  data-net:
    name: data-net
    external: true
